security:
  secret:
    key: vodZHjPmI9sWupUDFvNrzlmal60L7I1vdc4MpNC4S0hFdgtXBkndMpbkCBUURaWcL2kvfdKXUkKeSW87qUYwbnOoFqf63MC6w264OKstT0GzS1oUZS6Uk1ify57FX5VW8yLSsX5nqxeRwR2UAVfRYH1M6SgfIjvpVI+5gNRxrt75iQ1pwlVaRCJ0Gu2/Fs1OAWWGsKH8fHK7l4Lj2YOZmY40gEtIH+o+FIzF3Gs07KxTmZR8oT0oaXN4REgQ9oLGDuwFlRjIQoGYyqxka+kmDd0yAw2AOHX2/bGE2iRfZd8+51W2CDM/cIWR/i3LRyhaR+DL8Q/uPZHMvv4ArZWOEH/R+DWiHK0ci7JykoYgzVQ=
  jwt:
    expired_after_ms: 86400000 # 24 hours

spring:
  datasource:
    url: jdbc:mysql://3.34.185.156:3306/monochrome?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: monochrome
    password: Full505@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect